### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by mocxd** [MaxMotovilov/node-promise#7]
(I believe) the following code has a typo:

```
var Promise = require("promise").Promise;
var promise = new Promise();
asyncOperation(function(){
  Promise.resolve("succesful result");
});
promise -> given to the consumer
```

should be `promise.resolve("succesful result");` correct?

**Comment by MaxMotovilov** [comment]
https://github.com/MaxMotovilov/node-promise/commit/f4018de675b5373a484ad24738336160e60f797a
